administrador_inicio:
    path:  /
    defaults: { _controller: "CpdgAdministradorBundle:Inicio:index" }
administrador_inicio_login_error:
    path:  /loginError
    defaults: { _controller: "CpdgAdministradorBundle:Inicio:loginError" }
    methods:  [GET, POST]
administrador_inicio_login:
    path:  /login
    defaults: { _controller: "CpdgAdministradorBundle:Inicio:login" }
administrador_inicio_login_check:
    path: /login_check
administrador_inicio_logout:
    path: /logout
    defaults: { _controller: "CpdgAdministradorBundle:Inicio:logout" }
administrador_inicio_logoutbridge:
    path: /logoutBridge
    defaults: { _controller: "CpdgAdministradorBundle:Inicio:logoutBridge" }