proveedores_index:
    path:     /
    defaults: { _controller: "CpdgAdministradorBundle:Proveedores:index" }
    methods:  [GET, POST]

proveedores_show:
    path:     /{id}/show
    defaults: { _controller: "CpdgAdministradorBundle:Proveedores:show" }
    methods:  [GET, POST]

proveedores_new:
    path:     /new
    defaults: { _controller: "CpdgAdministradorBundle:Proveedores:new" }
    methods:  [GET, POST]

proveedores_edit:
    path:     /{id}/edit
    defaults: { _controller: "CpdgAdministradorBundle:Proveedores:edit" }
    methods:  [GET, POST]

proveedores_delete:
    path:     /{id}/delete
    defaults: { _controller: "CpdgAdministradorBundle:Proveedores:delete" }
    methods:  [GET, POST]
proveedores_exportarExcel:
    path:     /exportarExcel
    defaults: { _controller: "CpdgAdministradorBundle:Proveedores:exportarExcel" }
    methods:  [GET, POST]
proveedores_loadFile:
    path:     /loadFile
    defaults: { _controller: "CpdgAdministradorBundle:Proveedores:loadFile" }
    methods:  [GET, POST]
