proveedoresusuarios_index:
    path:     /
    defaults: { _controller: "CpdgAdministradorBundle:ProveedoresUsuarios:index" }
    methods:  [GET, POST]

proveedoresusuarios_show:
    path:     /{id}/show
    defaults: { _controller: "CpdgAdministradorBundle:ProveedoresUsuarios:show" }
    methods:  [GET, POST]

proveedoresusuarios_new:
    path:     /new
    defaults: { _controller: "CpdgAdministradorBundle:ProveedoresUsuarios:new" }
    methods:  [GET, POST]

proveedoresusuarios_edit:
    path:     /{id}/edit
    defaults: { _controller: "CpdgAdministradorBundle:ProveedoresUsuarios:edit" }
    methods:  [GET, POST]

proveedoresusuarios_delete:
    path:     /{id}/delete
    defaults: { _controller: "CpdgAdministradorBundle:ProveedoresUsuarios:delete" }
    methods:  [GET, POST]
