usuario_inicio:
    path:  /
    defaults: { _controller: "CpdgUsuarioBundle:Inicio:index" }
usuario_inicio_login_error:
    path:  /loginError
    defaults: { _controller: "CpdgUsuarioBundle:Inicio:loginError" }
    methods:  [GET, POST]
usuario_inicio_login:
    path:  /login
    defaults: { _controller: "CpdgUsuarioBundle:Inicio:login" }
usuario_inicio_login_check:
    path: /login_check
usuario_inicio_logout:
    path: /logout
    defaults: { _controller: "CpdgUsuarioBundle:Inicio:logout" }
usuario_inicio_logoutbridge:
    path: /logoutBridge
    defaults: { _controller: "CpdgUsuarioBundle:Inicio:logoutBridge" }